version: "3.7"



services:
  web:
    build:
      context: ./verification
      dockerfile: Dockerfile
    command: gunicorn verification.wsgi:application --bind 0.0.0.0:8001
    ports:
      - 8001:8001
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

volumes:
  postgres_data: